// Every `op` discriminant, for validation and exhaustiveness checks.
//
// Split out of `tree-op-types.ts`, which was against its line cap; re-exported from there so
// every importer keeps its path. The type import is type-only, so the cycle between the two
// files is erased at runtime.

import type { TreeDocOpKind } from './tree-op-types.ts';

/** Every {@link TreeDocOpKind}, for validation and exhaustiveness checks. */
export const TREE_DOC_OP_KINDS = [
  'replaceStoryBlocks',
  'insertText',
  'deleteText',
  'setParagraphMarkRevision',
  'proposeParagraphMerge',
  'insertCommentMarker',
  'acceptRevision',
  'rejectRevision',
  'acceptAllRevisions',
  'rejectAllRevisions',
  'insertTab',
  'insertHardBreak',
  'insertPageBreak',
  'insertPageField',
  'setFieldCode',
  'setListLevel',
  'setListNumbering',
  'setParagraphTabStops',
  'setParagraphMarkProperties',
  'splitParagraph',
  'splitParagraphMany',
  'joinParagraphs',
  'setRunProperties',
  'setParagraphProperties',
  'setSectionProperties',
  'setSectionMark',
  'insertHyperlink',
  'setHyperlinkTarget',
  'removeHyperlink',
  'setMathEquation',
  'removeMathEquation',
  'setContentControlValue',
  'removeContentControl',
  'insertInlineContentControl',
  'addRepeatingSectionItem',
  'removeRepeatingSectionItem',
  'deleteBlock',
  'insertTable',
  'insertTableRow',
  'deleteTableRow',
  'insertTableColumn',
  'deleteTableColumn',
  'setTableColumnWidths',
  'setTableRightEdgeWidth',
  'setTableRowHeight',
  'setTableProperties',
  'authorTable',
  'setTableCellBorders',
  'setTableCellFill',
  'setTableCellVerticalAlignment',
  'createHeaderFooter',
  'deleteHeaderFooter',
  'linkToPrevious',
  'unlinkFromPrevious',
  'setSectionFurnitureOptions',
  'setDocumentProtection',
  'insertNote',
  'deleteNote',
  'convertNote',
  'convertAllNotes',
  'setNoteProperties',
  'setContentControlProperties',
  'insertContentControl',
  'wrapBlocksInContentControl',
  'insertFragment',
  'insertDrawing',
  'replaceDrawingResource',
  'deleteDrawing',
  'resizeDrawing',
  'cropDrawing',
  'positionDrawing',
  'setDrawingWrap',
  'setDrawingMetadata',
  'setDrawingLocks',
  'transformDrawing',
  'insertToc',
  'replaceTocResult',
  'rewriteTocPageNumbers',
  'refreshFieldResults',
  'setTextFormFieldDefault',
  'commitTextFormField',
  'setLegacyCheckbox',
  'setLegacyDropdown',
  'insertBuildingBlock',
] as const satisfies readonly TreeDocOpKind[];

// Compile-time exhaustiveness, matching the legacy `DOC_OP_KINDS` guard: a new op must be
// listed here or this fails to typecheck, so it can never be silently unvalidated.
type _MissingTreeOp = Exclude<TreeDocOpKind, (typeof TREE_DOC_OP_KINDS)[number]>;
const _treeOpsExhaustive: _MissingTreeOp extends never ? true : ['missing', _MissingTreeOp] = true;
void _treeOpsExhaustive;
